<?php
/* @var \BluePsyduck\ManiaScriptCollection\Script\Script $script */
$script = $this->script;
?>
<li class="content-box script" data-script="<?php echo $this->escape($script->getName()); ?>">
    <div class="checkbox"><input type="checkbox" name="<?php echo $script->getName(); ?>" /></div>
    <div class="text">
        <h4><?php echo $this->escape($script->getName()); ?></h4>
        <span class="description"><?php echo $this->escape($script->getDescription()); ?></span>
        <dl class="legend">
            <dt>Website:</dt>
            <dd><a href="<?php echo $this->escape($script->getWebsite()); ?>" target="_blank"><?php echo $this->escape($script->getWebsite()); ?></a></dd>
            <dt>Source:</dt>
            <dd><a href="<?php echo $this->escape($script->getSource()); ?>" target="_blank"><?php echo $this->escape($script->getSource()); ?></a></dd>
            <dt>Namespace:</dt>
            <dd><?php echo $this->escape($script->getNamespace()); ?></dd>
            <dt>Dependencies:</dt>
            <dd><?php echo $this->escape($this->implodeList($script->getDependencies())); ?></dd>
            <dt>Conflicts:</dt>
            <dd><?php echo $this->escape($this->implodeList($script->getConflicts())); ?></dd>
        </dl>
    </div>
</li>