<section class="usage">
    <h3 class="content-title">Usage</h3>
    <div class="content-box">
        <div class="description">Select the scripts to include from the list, and copy&amp;paste the code into your ManiaLink file.</div>
        <div class="output">
            <input
                id="usageOutput"
                type="text"
                data-script-url="<?php echo $this->scriptUrl(); ?>"
                value="Please enable JavaScript to see the generated output."
                readonly="readonly"
            /></div>
    </div>
</section>