<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>ManiaScript Collection powered by Mania-Community.de</title>
        <link rel="stylesheet" href="assets/css/reset.css">
        <link rel="stylesheet" href="assets/css/base.css">
        <script src="assets/js/jquery/jquery-2.1.1.min.js"></script>
        <script src="assets/js/base.js"></script>
    </head>
    <body>
        <header><img src="assets/img/header.png" alt="ManiaScript Collection" /></header>
        <div id="content">
            <?php echo $this->partial('partial/usage.phtml'); ?>

            <section id="scripts">
                <h1>Available Scripts</h1>
                <?php foreach ($this->scripts as $name => $group) { ?>
                    <section class="script-group">
                        <h3 class="content-title">Group: <?php echo $this->escape($name); ?></h3>
                        <ul><?php
                            foreach ($group as $script) {
                                echo $this->partial('partial/script.phtml', array('script' => $script));
                            }
                        ?></ul>
                    </section>
                <?php } ?>
            </section>
        </div>
        <footer>
            &copy;<?php echo date('Y'); ?> ManiaScript Collection<br />
            Powered by <a href="http://www.mania-community.de">Mania-Community.de</a>
        </footer>
    </body>
</html>